export const UPDATE_USERINFO = 'UPDATE_USERINFO';

export const UPDATE_SETTING = 'UPDATE_SETTING';

export const UPDATE_AUTH_STATUS = 'UPDATE_AUTH_STATUS';
// export const UPDATE_LIMIT = 'UPDATE_LIMIT';

// export const SWITCH_MARK = 'SWITCH_MARK';


// export const UPDATE_TYPE = 'UPDATE_TYPE';